- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
- src/main/resources/application.properties
Setup environments and added config to application.properties to create database
> Setup environments + h2 config

- pom.xml
Added OpenAPi, AssertJ, Junit5
> Modified POM for new dependencies

- src/main/java/com/gfttraining/users/Repositoy/UserRepository.java
> ADD UserRepository

- pom.xml
- src/main/java/com/gfttraining/users/model/User.java
- src/main/java/com/gfttraining/users/repository/UserRepository.java
- src/test/java/com/gfttraining/users/UsersApplicationTests.java
Added UserRepositoryTest and fixed some issues in UserRepository and User classes
> ADD UserRepositoryTest + FIX UserRepository + FIX User

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/services/UserService.java
- src/test/java/com/gfttraining/users/controllers/UserControllerTest.java
UserService's methods changed so that they return an object instead of a response, and changed controller to tolerate these changes.
> REFACTOR User Service to return object

- src/main/java/com/gfttraining/users/models/User.java
- src/test/java/com/gfttraining/users/UsersApplicationTest.java
- src/test/java/com/gfttraining/users/models/PaymentMethodTest.java
- src/test/java/com/gfttraining/users/models/UserTest.java
Added coverage for User and Payment Methods and fixed getters and setters on User class
> ADD coverage for every entity + FIX getter and setters

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/services/UserService.java
- src/test/java/com/gfttraining/users/controllers/UserControllerTest.java
Added DeleteUserById test and the initialization of DeleteUserById method
> ADD DeleteUserById test + ADD initialization of DeleteUserById method

- src/test/java/com/gfttraining/users/UsersApplicationTest.java
- src/test/java/com/gfttraining/users/models/PaymentMethodTest.java
- src/test/java/com/gfttraining/users/models/UserTest.java
Added @DisplayName tag to every test method
> ADD @DisplayName to every test

- src/test/java/com/gfttraining/users/UsersApplicationTest.java
- src/test/java/com/gfttraining/users/controllers/UserControllerTest.java
Added internal_server_error tests to controller to complete 100% coverage
> ADD internal_server_error tests to controller

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/resources/application-dev.properties
- src/main/resources/application-dev.yaml
- src/main/resources/application-prod.properties
- src/main/resources/application-prod.yaml
- src/main/resources/application.properties
- src/main/resources/application.yaml
- src/test/java/com/gfttraining/users/models/UserTest.java
Refactored properties format to yaml
> REFACTOR properties format to yaml

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/services/UserService.java
- src/test/java/com/gfttraining/users/controllers/UserControllerTest.java
> ADD loadListOfUsers

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/services/UserService.java
- src/test/java/com/gfttraining/users/controllers/UserControllerTest.java
> ADD updateUserById

- pom.xml
- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/models/PaymentMethod.java
- src/main/java/com/gfttraining/users/models/User.java
Added Jakarta Validators and deleted constructors in models with lombok annotations
> ADD Jakarta Validators

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/repositories/UserRepository.java
- src/main/java/com/gfttraining/users/services/UserService.java
> ADD getUserByName

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/repositories/UserRepository.java
- src/main/java/com/gfttraining/users/services/UserService.java
Fixed method getUserByName to return a list in case of more than one user with the same name
> FIX getUserByName returning a List

- src/main/java/com/gfttraining/users/initdata/DataInitializer.java
Added some objects to database on initialization
> ADD DataInitializer

- src/main/java/com/gfttraining/users/controllers/FavoriteController.java
- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/models/Favorite.java
- src/main/java/com/gfttraining/users/models/FavoritePK.java
- src/main/java/com/gfttraining/users/models/FavoriteRequest.java
- src/main/java/com/gfttraining/users/models/User.java
- src/main/java/com/gfttraining/users/repositories/FavoriteRepository.java
- src/main/java/com/gfttraining/users/services/FavoriteService.java
- src/main/java/com/gfttraining/users/services/UserService.java
Added favorite repository, service and model with the correct Primary Key
> ADD Favorite full functionality

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/models/UserRequest.java
- src/main/java/com/gfttraining/users/repositories/PaymentMethodRepository.java
- src/main/java/com/gfttraining/users/services/UserService.java
Now the system can receive users with paymentMethod as a String. ToDo negative validations
> REFACTOR receive UserRequest in UserController methods

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/test/java/com/gfttraining/users/controllers/UserControllerIT.java
- src/test/java/com/gfttraining/users/controllers/UserControllerTest.java
- src/test/resources/application.properties
- src/test/resources/logback-test.xml
Mokcito tests revisited and fixed + first integration test created + now test trace is cleaner with logback
> ADD testCreateUser integration test + clean trace with logback + REFACTOR some tests to accept UserRequest

- src/main/java/com/gfttraining/users/services/UserService.java
Refactored updateUserById method in order to be required a complete User to update an existing User
> REFACTOR updateUserById to need a complete user for updating

- src/main/java/com/gfttraining/users/controllers/FavoriteController.java
- src/main/java/com/gfttraining/users/models/FavoritePK.java
- src/main/java/com/gfttraining/users/models/FavoriteRequest.java
- src/main/java/com/gfttraining/users/repositories/FavoriteRepository.java
- src/main/java/com/gfttraining/users/services/FavoriteService.java
Added deleteFavorite and refactored "productId" to "product" in Favorite and FavoriteRequest
> ADD deleteFavorite + REFACTOR args in Favorite and FavoriteRequest

- src/main/java/com/gfttraining/users/controllers/UserController.java
- src/main/java/com/gfttraining/users/services/UserService.java
> ADD getListOfUsers

- pom.xml
- src/main/java/com/gfttraining/users/controllers/UserController.java
Fixed some errors in POM from the Tomcat instalation
> FIX fatal errors

- src/main/java/com/gfttraining/users/controllers/UserControllerAdvice.java
- src/main/java/com/gfttraining/users/models/Country.java
- src/main/java/com/gfttraining/users/models/UserRequest.java
Added handler for CountryNotFoundException returning 404 and the message
> ADD handler for CountryNotFoundException

- src/main/java/com/gfttraining/users/controllers/FavoriteController.java
- src/main/java/com/gfttraining/users/models/FavoriteRequest.java
- src/main/java/com/gfttraining/users/services/UserService.java
Fixed some favorite conflics with validation
> FIX conflicts

- pom.xml
- src/main/java/com/gfttraining/users/controllers/FavoriteController.java
- src/main/java/com/gfttraining/users/models/FavoriteRequest.java
- src/main/java/com/gfttraining/users/repositories/FavoriteRepository.java
- src/main/java/com/gfttraining/users/services/CountryService.java
- src/main/java/com/gfttraining/users/services/FavoriteService.java
- src/test/java/com/gfttraining/users/controllers/FavoriteControllerIT.java
- src/test/java/com/gfttraining/users/controllers/FavoriteControllerTest.java
- src/test/java/com/gfttraining/users/services/FavoriteServiceIT.java
- src/test/java/com/gfttraining/users/services/FavoriteServiceTest.java
Added all tests and configured POM for WebTestClient
> ADD Favorite Unit Tests and Integration Tests
